name: "✨ Feature request"
description: "Suggest an idea or enhancement."
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement!
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: "What problem are you trying to solve?"
      placeholder: "I'm always frustrated when..."
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: "What would you like to see?"
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: "Any alternative solutions or features you've considered."
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: "Add any other context or screenshots."
    validations:
      required: false
